# Site settings
title: Сергей Удалов
email: sergei.udalov@gmail.com
description: Здесь я излагаю свое мировоззрение. Меня итересует космология, физика, история и политика. Давайте разбираться и обсуждать.
baseurl: ""
url: "http://www1.sergei-udalov.ru"
github: sergio-fry
twitter: SergeiUdalov

# Build settings
markdown: kramdown
permalink: pretty
